# Site settings
title: Andres Alcaraz
email: andresalcarazhurd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog. Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "andresalcaraz.github.io" # the base hostname & protocol for your site
twitter_username: aalcarazh
github_username:  andresalcaraz

# Build settings
markdown: kramdown
